# Generated by Django 4.0.8 on 2025-11-17 03:25

import ckeditor.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Libeller du role')),
                ('can_read', models.BooleanField(default=False, verbose_name='Peut Lire')),
                ('can_create', models.BooleanField(default=False, verbose_name='Peut Créer')),
                ('can_update', models.BooleanField(default=False, verbose_name='Peut Mettre a jour')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Peut Supprimer')),
                ('is_active', models.BooleanField(default=True, help_text='Defini la visibilite', verbose_name='Actif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur du menu')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du role')),
                ('code', models.IntegerField(null=True, verbose_name='Code du menu')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='Lien du menu')),
                ('is_active', models.BooleanField(default=True, help_text='Defini la visibilite', verbose_name='Actif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur du menu')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googlemap', models.CharField(max_length=1024, null=True, verbose_name='Lien google map du lieu physique')),
                ('type_identification', models.IntegerField(default=1, null=True, verbose_name="Type de la pièce d'identité")),
                ('identification', models.FileField(null=True, storage=core.models.UUIDFileStorageIDRECTOVERSO(), upload_to='cni_recto_verso', verbose_name="Pièce d'identification")),
                ('identificationID', models.CharField(max_length=1024, null=True, verbose_name='Numéro de la pièce identité')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Numero de telephone')),
                ('whatsapp_phone', models.CharField(max_length=255, null=True, verbose_name='Numero de telephone Whatsapp')),
                ('address', models.CharField(max_length=254, verbose_name='Adresse')),
                ('codepostal', models.CharField(max_length=254, null=True, verbose_name='Boite Postal')),
                ('birthday_date', models.DateField(null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(max_length=254, null=True, verbose_name='Sexe')),
                ('language', models.CharField(default='french', max_length=20, verbose_name='Adresse')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Monnaie')),
                ('rate', models.IntegerField(default=0, verbose_name='Mention de lutilisateur')),
                ('pp', models.FileField(null=True, storage=core.models.UUIDFileStoragePP(), upload_to='pp', verbose_name='Image de profile')),
                ('cover', models.FileField(null=True, storage=core.models.UUIDFileStorageCOVER(), upload_to='cover', verbose_name='Image de couverture du profile')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff ou Pas')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Client ou Pas')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte Verifier ou pas')),
                ('googleauthenticator', models.BooleanField(default=False, verbose_name='Google Authenticator Actif ou pas')),
                ('twofactor', models.BooleanField(default=False, verbose_name='Authentification a deux facteurs Actif ou pas')),
                ('googlemapservice', models.BooleanField(default=False, verbose_name='Service Google Map Actif ou pas')),
                ('pushconfirmnotification', models.BooleanField(default=False, verbose_name='Push Notification pour confirmation Actif ou pas')),
                ('smsconfirmnotification', models.BooleanField(default=False, verbose_name='Sms Notification pour confirmation Actif ou pas')),
                ('emailconfirmnotification', models.BooleanField(default=False, verbose_name='Email Notification pour confirmation Actif ou pas')),
                ('pushremindnotification', models.BooleanField(default=False, verbose_name='Push Notification des rappels Actif ou pas')),
                ('smsremindnotification', models.BooleanField(default=False, verbose_name='Sms Notification des rappels Actif ou pas')),
                ('emailremindnotification', models.BooleanField(default=False, verbose_name='Email Notification des rappels Actif ou pas')),
                ('pushpricealertnotification', models.BooleanField(default=False, verbose_name="Push Notification des prix d'alert Actif ou pas")),
                ('smspricealertnotification', models.BooleanField(default=False, verbose_name="Sms Notification des prix d'alert Actif ou pas")),
                ('emailpricealertnotification', models.BooleanField(default=False, verbose_name="Email Notification des prix d'alert Actif ou pas")),
                ('pushdiscountnotification', models.BooleanField(default=False, verbose_name='Push Notification des offres Actif ou pas')),
                ('smsdiscountnotification', models.BooleanField(default=False, verbose_name='Sms Notification des offres Actif ou pas')),
                ('emaildiscountnotification', models.BooleanField(default=False, verbose_name='Email Notification des offres Actif ou pas')),
                ('is_active', models.BooleanField(default=True, help_text='Defini la visibilite', verbose_name='Actif')),
                ('is_online', models.BooleanField(default=False, help_text="Defini si l'utilsateur est en ligne", verbose_name='En ligne')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('last_updated_password_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour du mot de passe')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du role')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description du role')),
                ('is_active', models.BooleanField(default=True, help_text='Defini la visibilite', verbose_name='Actif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur du role')),
                ('permissions', models.ManyToManyField(to='core.menurules', verbose_name='Menu lier au role')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Commentaire')),
                ('is_active', models.BooleanField(default=True, help_text='Defini la visibilite', verbose_name='Actif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personne ayant attribuer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons', verbose_name='Personne ayant acces au center')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profil', verbose_name='Profil Attribuer a lutilisateur')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date et heur de connexion')),
                ('logout_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date et heur de Deconnexion')),
                ('location', models.TextField(verbose_name='Localisation')),
                ('devise', models.TextField(verbose_name='Appareil utiliser')),
                ('ip_address', models.TextField(verbose_name='Adresse IP utiliser')),
                ('mac_address', models.TextField(verbose_name="Adresse MAC de l'appareil utiliser")),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons', verbose_name='Information de lutilisateur')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ParentMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du menu parent')),
                ('label', models.TextField(null=True, verbose_name='Label du menu parent')),
                ('icon', models.CharField(max_length=25, null=True, verbose_name='Icon du menu parent')),
                ('is_active', models.BooleanField(default=True, help_text='Defini la visibilite', verbose_name='Actif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur du menu')),
                ('menus', models.ManyToManyField(to='core.menus', verbose_name='Menu Enfant lier')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='menurules',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.menus', verbose_name='Menu Concerner'),
        ),
        migrations.CreateModel(
            name='AccountActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code de validation')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Code Expirer ou pas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Client actif ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons', verbose_name='Information de lutilisateur')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
