# Generated by Django 4.0.8 on 2025-12-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='referral',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reference', to=settings.AUTH_USER_MODEL),
        ),
    ]
