# Generated by Django 4.0.8 on 2025-12-17 02:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcaracteristque',
            name='attribut_price',
        ),
        migrations.RemoveField(
            model_name='productcaracteristque',
            name='label',
        ),
        migrations.RemoveField(
            model_name='productcaracteristque',
            name='value',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='commission',
        ),
        migrations.AddField(
            model_name='products',
            name='commission_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage de la commission de lentreprise'),
        ),
        migrations.AddField(
            model_name='products',
            name='commission_provider',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage de la commission du fournisseur'),
        ),
        migrations.CreateModel(
            name='DefaultsMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la matiere')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Description du materiau')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible ou pas')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Infos sur l'auteur")),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
        migrations.CreateModel(
            name='DefaultSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Valeur de la taille')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible ou pas')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Infos sur l'auteur")),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
        migrations.CreateModel(
            name='DefaultsColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='choix de couleur')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='code de couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='visible ou pas')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Infos sur l'auteur")),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
        migrations.AddField(
            model_name='productcaracteristque',
            name='color',
            field=models.ManyToManyField(to='dashboard.defaultscolors', verbose_name='choix des couleurs du produit'),
        ),
        migrations.AddField(
            model_name='productcaracteristque',
            name='material',
            field=models.ManyToManyField(to='dashboard.defaultsmaterial', verbose_name='choix des matières du produit'),
        ),
        migrations.AddField(
            model_name='productcaracteristque',
            name='size',
            field=models.ManyToManyField(to='dashboard.defaultsize', verbose_name='choix tailles du produits'),
        ),
    ]
