# Generated by Django 4.0.8 on 2025-12-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_productcaracteristque_attribut_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='depth',
            field=models.CharField(max_length=250, null=True, verbose_name='profondeur'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.CharField(max_length=250, null=True, verbose_name='hauteur'),
        ),
        migrations.AddField(
            model_name='products',
            name='weigth',
            field=models.CharField(max_length=250, null=True, verbose_name='poids'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.CharField(max_length=250, null=True, verbose_name='largeur'),
        ),
    ]
