# Generated by Django 4.0.8 on 2025-12-17 06:32

import ckeditor.fields
import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('dashboard', '0003_products_depth_products_height_products_weigth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Titre du Blog')),
                ('label', models.TextField(null=True, verbose_name='Label du Blog')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Description du blog')),
                ('is_approuved', models.BooleanField(default=False, verbose_name='Blog Approuvé ou pas')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('cover', models.FileField(storage=dashboard.models.UUIDFileStorageCOVER(), upload_to='blog/cover/', verbose_name='Couverture de du blog')),
                ('is_active', models.BooleanField(default=True, verbose_name='Blog actif ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('approuved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlogAdminAppouved', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(storage=dashboard.models.UUIDFileStorageCOVER(), upload_to='blog/image/', verbose_name='image de du blog')),
                ('is_active', models.BooleanField(default=True, verbose_name='Blog actif ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
            ],
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=dashboard.models.UUIDFileStorageVIDEO(), upload_to='blog/video/', verbose_name='Video de du blog')),
                ('is_active', models.BooleanField(default=True, verbose_name='Blog actif ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
            ],
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='Like ou pas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Blog Like actif ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.blog', verbose_name='Blog Concerné')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons', verbose_name='Information sur celui qui a commenté')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(verbose_name='Commentaire du blog')),
                ('is_block', models.BooleanField(default=False, verbose_name='Commentaire bloquer ou pas')),
                ('is_active', models.BooleanField(default=True, verbose_name='FAQ actif ou pas')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise a jour')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.blog', verbose_name='Blog Concerné')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons', verbose_name='Information sur celui qui a commenté')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(to='dashboard.blogimage', verbose_name='Image du Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='videos',
            field=models.ManyToManyField(to='dashboard.blogvideo', verbose_name='Video du Blog'),
        ),
    ]
