# Generated by Django 4.0.8 on 2025-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_blog_blogimage_blogvideo_bloglike_blogcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='provider_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Montant à transmettre au Fournisseur'),
        ),
        migrations.AddField(
            model_name='finances',
            name='provider_is_pay',
            field=models.BooleanField(default=False, verbose_name='Fournisseur a ete payer ou pas'),
        ),
    ]
