# Generated by Django 4.0.8 on 2025-12-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_finances_provider_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskets',
            name='is_checkout',
            field=models.BooleanField(default=False, verbose_name='panier payer ou pas'),
        ),
    ]
