# Generated by Django 4.0.8 on 2025-12-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_baskets_is_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='delivery_end_datetime',
            field=models.DateTimeField(null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='commands',
            name='delivery_start_datetime',
            field=models.DateTimeField(null=True, verbose_name='Heure de debut'),
        ),
        migrations.AddField(
            model_name='commands',
            name='is_delivery_end',
            field=models.BooleanField(default=False, verbose_name='Commande livrer ou pas'),
        ),
        migrations.AddField(
            model_name='commands',
            name='is_delivery_start',
            field=models.BooleanField(default=False, verbose_name='Commande a livrer ou pas'),
        ),
    ]
