# Generated by Django 4.0.8 on 2025-12-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_commands_delivery_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='commission',
        ),
    ]
