# Generated by Django 4.0.8 on 2025-12-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_company_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoringproducts',
            name='seller',
        ),
        migrations.AddField(
            model_name='sponsoringproducts',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.providers', verbose_name='information sur le magasin'),
        ),
    ]
