# Generated by Django 4.0.8 on 2025-12-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_sponsoringproducts_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.defaultscolors', verbose_name='choix de la couleur du produit'),
        ),
        migrations.AddField(
            model_name='commands',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.defaultsmaterial', verbose_name='choix de la matiere du produit'),
        ),
        migrations.AddField(
            model_name='commands',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.defaultsize', verbose_name='choix de la taille du produit'),
        ),
        migrations.AddField(
            model_name='productbaskets',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.defaultscolors', verbose_name='choix de la couleur du produit'),
        ),
        migrations.AddField(
            model_name='productbaskets',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.defaultsmaterial', verbose_name='choix de la matiere du produit'),
        ),
        migrations.AddField(
            model_name='productbaskets',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.defaultsize', verbose_name='choix de la taille du produit'),
        ),
    ]
