# Generated by Django 4.0.8 on 2025-12-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_commands_color_commands_material_commands_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskets',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='prix total de la commande'),
        ),
        migrations.AlterField(
            model_name='productbaskets',
            name='one_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='prix total'),
        ),
    ]
