"""
Django settings for fstore project.

Generated by 'django-admin startproject' using Django 4.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pbi)un&2nl8%l%4*tg9)ryyq_-^d1(m#1l977bi%srbexv4_x3'

SHOW_DEBUG_BAR = config('SHOW_DEBUG_BAR', default=False, cast=bool)

COMPRESS_ENABLED = config('COMPRESS_ENABLED', default=True, cast=bool)

DEBUG = config('DEBUG', default=True, cast=bool)

def is_debug_on():
    if DEBUG:
        return True
    else:
        return False
    
ALLOWED_HOSTS = ['*']

if not DEBUG:
    #  SESSION_COOKIE_HTTPONLY = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_DOMAIN= 'fstore.com'
    CSRF_TRUSTED_ORIGINS = ['fstore.com',]
    SECURE_HSTS_SECONDS = 1
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_HTTPONLY = True

# Application definition
LIBS = [
    'allauth',
    'allauth.account',
    'gunicorn',
    'widget_tweaks',
    'password_reset',
    'django_countries',
    'cacheops',
    'oauth2_provider',
    'corsheaders',
    'django_q',
    'easy_thumbnails',
    'channels',
    'django_filters',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'cities_light',
    'django_cleanup.apps.CleanupConfig',
    'captcha'
]

FRAMEWORKS_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

# les apps du system total
APPS = [
    'core',
    'api',
    'dashboard',
]

INSTALLED_APPS = LIBS + FRAMEWORKS_APPS + APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'fstore.urls'

WSGI_APPLICATION = 'fstore.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'fstore', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #Core Preprocessor
                'core.auth_preprocessor.define_usertype',
            ],
        },
    },
]

SESSION_COOKIE_AGE = 3600  # Session expires after 60 minutes of inactivity
SESSION_SAVE_EVERY_REQUEST = True

# Daphne
ASGI_APPLICATION = 'fstore.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Try localhost or 127.0.0.1 as per your machine configurations
            "hosts": [("127.0.0.1", 6379)]
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'    : 'django.db.backends.mysql',
        'NAME'      : config('DB_NAME'),
        'USER'      : config('DB_USER'),
        'PASSWORD'  : config('DB_PASSWORD'),
        'HOST'      : config('DB_HOST'),
        'PORT'      : config('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':25
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# email settings
#DEFAULT_FROM_EMAIL = "MABOUNIA <no_reply@mabounia.com>"
EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr-cm'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'

#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ROOT_PATH = os.path.dirname(__file__)

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

CKEDITOR_UPLOAD_PATH = 'media/uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SEXE = (
    ('', 'Choisir le sexe'),
    ('Masculin', 'Masculin'),
    ('Féminin', 'Féminin'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Api Afpay
AFPAY_INIT_BASE_URL         = config('AFPAY_INIT_BASE_URL')
AFPAY_BASE_URL              = config('AFPAY_BASE_URL')
AFPAY_API_PUBLIC_KEY        = config('AFPAY_API_PUBLIC_KEY')
AFPAY_API_KEY_SECRET        = config('AFPAY_API_KEY_SECRET')
AFPAY_API_ACCOUNT_USERNAME  = config('AFPAY_API_ACCOUNT_USERNAME')
AFPAY_API_ACCOUNT_PASSWORD  = config('AFPAY_API_ACCOUNT_PASSWORD')